---
title: "SouthAfrica_output"
author: "Kevin Little"
date: "3/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(jsonlite)
library(tidyverse)
library(httr)

source('functions.R')

data_file_country <- paste0('data/country_data_', as.character(Sys.Date()), '.csv')


defStartdate <- NA
defBuffer <- 7
#defBaseline is the default value of points to use to compute the exponential growth control limits
defBaseline <- 20

if (!file.exists(data_file_country)) {
  #covid_data <- httr::GET("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv", 
  covid_data <- httr::GET("https://covid.ourworldindata.org/data/owid-covid-data.csv",
                          authenticate(":", ":", type="ntlm"),
                          write_disk(data_file_country, overwrite=TRUE))
}

df_country <- read.csv(data_file_country,
                       header = TRUE,
                       stringsAsFactors = FALSE)

#remove NA values at the start of the series STARTING POINT DEPENDS ON SERIES

df_country <- df_country[!is.na(df_country$total_cases), ]



df_country <- df_country[df_country$location == "South Africa",]

#df_country$state          <- df_country$countriesAndTerritories
df_country$state          <- df_country$location
#df_country$datex          <- as.Date(df_country$dateRep, format = '%d/%m/%Y')
df_country$datex          <- as.Date(df_country$date, format = '%Y-%m-%d')
#df_country$New_Deaths    <- df_country$deaths
df_country$New_var     <- ave(df_country$total_cases, df_country$state, FUN = function(x) { c(x[1], diff(x)) })
df_country$New_var_max <- ave(df_country$New_var, df_country$state, FUN = max)
df_country$level          <- 'country'

df_country$GEOID = rep(NA, nrow(df_country))

df_country$var_cum = rep(NA, nrow(df_country))

df_country <- df_country %>% 
              rename(GEO = level, NAME = state)

df_country <- df_country[c('GEOID', 'GEO', 'NAME', 'datex', 'var_cum','New_var', 'New_var_max')]

df_country$var_name <- "Cases"


df_all_raw <- find_phase_dates(data=df_country, adjust = FALSE, Epoch3_4_transition = 100)


df_all_raw$type <- 'raw'

df_all_adjusted <- find_phase_dates(data=df_country, adjust = TRUE, Epoch3_4_transition = 100)


df_all_adjusted$type <- 'adjusted'

df_all <- do.call(dplyr::bind_rows, list(df_all_raw, df_all_adjusted))

```

## South Africa Cases Plot



```{r plot_function, include = FALSE, warning = FALSE, fig.width = 8}
library(plotly)

graph_function <- function(data = df_var, title = NULL, subtitle = NULL){
  g <- ggplot(
          data = df_var,
          aes(
            x = datex,
            y = New_var)) +
          theme_bw() +
          geom_point(size = rel(1.25),alpha = 0.8) +
          geom_line(colour = "grey") +
          geom_line(
            aes(
              y = midline),
            color = 'red') +
          geom_line(
            aes(
              y = ucl),
            color = 'blue',
            linetype = 'dashed') +
          geom_line(
            aes(
              y = lcl),
            color = 'blue',
            linetype = 'dashed') +
          geom_point(
            aes(
              y = New_var_Dump),
            color = 'red') +
          scale_y_continuous(
            limits = c(0, max(20, 2 * max(df_var$New_var, na.rm = TRUE), max(df_var$New_var_Dump, na.rm = TRUE)))) +
          labs(
            title = paste0(title," as of ", as.character(Sys.Date() - 1)),
            subtitle = subtitle,
            #x = paste0(df_var$NAME[1],"_",df_var$var_name[1]),
            #y = paste(df_var$type[1], df_var$var_name[1]))
            x = "",
            y = "",
            caption = "Source: https://covid.ourworldindata.org")
  
  g1 <- ggplotly(g, dynamicTicks=TRUE)
  
  return(g1)
  
  
}


```



```{r plot, echo=FALSE, warning = FALSE, fig.width = 8}


df_all$lcl <- as.numeric(df_all$lcl)
df_all$New_var_Dump <- as.numeric(df_all$New_var_Dump)

#raw      
df_var <- df_all[df_all$var_name == "Cases" & df_all$type == "raw",]

title <-  "South Africa Reported Daily Cases from Covid-19"

graph_function(data = df_var, title = title) 

df_var <- df_all[df_all$var_name == "Cases" & df_all$type == "adjusted",] 

subtitle <- "Adjusted for day of week effect. Data source: https://covid.ourworldindata.org"

graph_function(data = df_var, title = title, subtitle = subtitle)  %>% 
  layout(title = list(text = paste0(title,
                      '<br>',
                      '<sup>',
                      subtitle,
                      '</sup>')))
```


